// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDttBWmj6KfFvX9DmpVfXpVCsj98QK12ns',
    appId: '1:507135990291:web:13f57f4388c415a4cf7de6',
    messagingSenderId: '507135990291',
    projectId: 'quilistapp',
    authDomain: 'quilistapp.firebaseapp.com',
    databaseURL: 'https://quilistapp-default-rtdb.firebaseio.com',
    storageBucket: 'quilistapp.appspot.com',
    measurementId: 'G-FCT69PKP5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRxQUWxIlXc9a9BtDZvDb2Sr6687TsXlw',
    appId: '1:507135990291:android:94f90a5534a88f64cf7de6',
    messagingSenderId: '507135990291',
    projectId: 'quilistapp',
    databaseURL: 'https://quilistapp-default-rtdb.firebaseio.com',
    storageBucket: 'quilistapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFrfLxMwjKHL58KH3Ne07KnMOuIchFOvo',
    appId: '1:507135990291:ios:829849144ba458a3cf7de6',
    messagingSenderId: '507135990291',
    projectId: 'quilistapp',
    databaseURL: 'https://quilistapp-default-rtdb.firebaseio.com',
    storageBucket: 'quilistapp.appspot.com',
    iosClientId: '507135990291-3gk28221b8tcqt8abdof40132sjgpljm.apps.googleusercontent.com',
    iosBundleId: 'com.example.quicklist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFrfLxMwjKHL58KH3Ne07KnMOuIchFOvo',
    appId: '1:507135990291:ios:829849144ba458a3cf7de6',
    messagingSenderId: '507135990291',
    projectId: 'quilistapp',
    databaseURL: 'https://quilistapp-default-rtdb.firebaseio.com',
    storageBucket: 'quilistapp.appspot.com',
    iosClientId: '507135990291-3gk28221b8tcqt8abdof40132sjgpljm.apps.googleusercontent.com',
    iosBundleId: 'com.example.quicklist',
  );
}
